### ISSUE TITLE
haproxy container restaring

### ISSUE THREAD

**Issue by iRhonin** [VZiChoushaDui/Libertea#3]
Hi, thank you for your effort to building this panel, I really like it!

I have a problem with my server, the `haproxy` container fails to start with the following error.
My server is Ubuntu 22.04.

```
[info] 022/201210 (1) : Hello HAProxy!.
[NOTICE]   (1) : haproxy version is 2.7.2-7e295dd
[NOTICE]   (1) : path to executable is /usr/local/sbin/haproxy
[WARNING]  (1) : config : parsing [/usr/local/etc/haproxy/haproxy.cfg:23]: 'log-format' overrides previous 'option httplog' in 'defaults' section.
[WARNING]  (1) : config : parsing [/usr/local/etc/haproxy/haproxy.cfg:83] : a 'http-request' rule placed after a 'use_backend' rule will still be processed before.
[WARNING]  (1) : config : parsing [/usr/local/etc/haproxy/haproxy.cfg:86] : a 'http-request' rule placed after a 'use_backend' rule will still be processed before.
[ALERT]    (1) : config : parsing [/usr/local/etc/haproxy/haproxy.cfg:88] : error detected while parsing ACL 'valid_panel' : failed to open pattern file </haproxy-files/lists/valid-panel-endpoints.lst>.
[ALERT]    (1) : config : parsing [/usr/local/etc/haproxy/haproxy.cfg:89] : error detected while parsing switching rule : no such ACL : 'valid_panel'.
[ALERT]    (1) : config : parsing [/usr/local/etc/haproxy/haproxy.cfg:91] : error detected while parsing ACL 'valid_user' : failed to open pattern file </haproxy-files/lists/valid-user-endpoints.lst>.
[ALERT]    (1) : config : parsing [/usr/local/etc/haproxy/haproxy.cfg:93] : error detected while parsing an 'http-request lua.auth-request' condition : no such ACL : 'valid_user'.
[ALERT]    (1) : config : Error(s) found in configuration file : /usr/local/etc/haproxy/haproxy.cfg
```

**Comment by VZiChoushaDui** [comment]
Hi @iRhonin 

The missing pattern files indicate that libertea-panel service is failing, as it should create these files on startup.

Can you post the content of `/tmp/libertea-panel.log` here so we can find what's wrong with it?

    tail --lines=500 /tmp/libertea-panel.log

**Comment by iRhonin** [comment]
Sorry for the late response, lost access to VPS because of the UFW configs, I am using non 22 SSH port which is a another issue.

```
tail --lines=500 /tmp/libertea-panel.log
```

```bash
*** Starting uWSGI 2.0.21 (64bit) on [Fri Jan 27 16:34:36 2023] ***
compiled with version: 11.3.0 on 23 January 2023 19:42:42
os: Linux-5.15.0-58-generic #64-Ubuntu SMP Thu Jan 5 11:43:13 UTC 2023
nodename: myhost.com
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 3
current working directory: /root/libertea/panel
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***
your processes number limit is 3719
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 127.0.0.1:1000 fd 4
uwsgi socket 0 bound to TCP address 127.0.0.1:44757 (port auto-assigned) fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***
Python version: 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x557ce8b38710
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 364600 bytes (356 KB) for 4 cores
*** Operational MODE: preforking ***
Traceback (most recent call last):
  File "/root/libertea/panel/./serve.py", line 4, in <module>
    from panel import create_app
  File "/root/libertea/panel/./panel/__init__.py", line 1, in <module>
    from . import utils
  File "/root/libertea/panel/./panel/utils.py", line 4, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 2091)
spawned uWSGI worker 1 (pid: 2173, cores: 1)
spawned uWSGI worker 2 (pid: 2174, cores: 1)
spawned uWSGI worker 3 (pid: 2175, cores: 1)
spawned uWSGI worker 4 (pid: 2176, cores: 1)
spawned uWSGI http 1 (pid: 2177)
```

**Comment by VZiChoushaDui** [comment]
@iRhonin It seems that there's an issue with a python dependency:

    ModuleNotFoundError: No module named 'requests'

We've fixed it. Please run the update command on your server, and check the log again.

    curl -s https://raw.githubusercontent.com/VZiChoushaDui/Libertea/master/bootstrap.sh -o /tmp/bootstrap.sh && bash /tmp/bootstrap.sh update

Let us know if the issue is resolved.

**Comment by iRhonin** [comment]
Thank you!
I am getting another error now:

```
*** Starting uWSGI 2.0.21 (64bit) on [Sat Jan 28 09:09:41 2023] ***
compiled with version: 11.3.0 on 23 January 2023 19:42:42
os: Linux-5.15.0-58-generic #64-Ubuntu SMP Thu Jan 5 11:43:13 UTC 2023
nodename: asdasdqew.net
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 3
current working directory: /root/libertea/panel
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***
your processes number limit is 3719
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 127.0.0.1:1000 fd 4
uwsgi socket 0 bound to TCP address 127.0.0.1:34207 (port auto-assigned) fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***
Python version: 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x55ff4511e710
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 364600 bytes (356 KB) for 4 cores
*** Operational MODE: preforking ***
Initializing...
SERVER_MAIN_IP: 185.81.114.162
[uwsgi-signal] signum 0 registered (wid: 0 modifier1: 0 target: default, any worker)
[uwsgi-signal] signum 1 registered (wid: 0 modifier1: 0 target: default, any worker)
Updating HAProxy lists
Traceback (most recent call last):
  File "/root/libertea/panel/./serve.py", line 10, in <module>
    app = TransLogger(create_app(), setup_console_handler=False)
  File "/root/libertea/panel/./panel/__init__.py", line 33, in create_app
    sysops.haproxy_update_users_list()
  File "/root/libertea/panel/./panel/sysops.py", line 39, in haproxy_update_users_list
    for user in users.find():
  File "/usr/local/lib/python3.10/dist-packages/pymongo/cursor.py", line 1248, in next
    if len(self.__data) or self._refresh():
  File "/usr/local/lib/python3.10/dist-packages/pymongo/cursor.py", line 1139, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "/usr/local/lib/python3.10/dist-packages/pymongo/mongo_client.py", line 1740, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/usr/local/lib/python3.10/dist-packages/pymongo/mongo_client.py", line 1685, in __start_session
    self._topology._check_implicit_session_support()
  File "/usr/local/lib/python3.10/dist-packages/pymongo/topology.py", line 538, in _check_implicit_session_support
    self._check_session_support()
  File "/usr/local/lib/python3.10/dist-packages/pymongo/topology.py", line 554, in _check_session_support
    self._select_servers_loop(
  File "/usr/local/lib/python3.10/dist-packages/pymongo/topology.py", line 238, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused, Timeout: 30s, Topology Description: <TopologyDescription id: 63d4e6640f4f3297f89ab8d0, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused')>]>
```

**Comment by VZiChoushaDui** [comment]
@iRhonin is the MongoDB container running properly? Run `docker ps`, and if it's running, check the logs again as it might've been fixed afterwards.

P.S. Your server's IP address was visible in the log you sent. I redacted it but nevertheless I suggest you change your server IP for security reasons.

**Comment by iRhonin** [comment]
> @iRhonin is the MongoDB container running properly? Run `docker ps`, and if it's running, check the logs again as it might've been fixed afterwards.
> 
> P.S. Your server's IP address was visible in the log you sent. I redacted it but nevertheless I suggest you change your server IP for security reasons.

Ops, thanks for noticing and removing it.

Mongo container is restarting with this log:
```
WARNING: MongoDB 5.0+ requires a CPU with AVX support, and your current system does not appear to have that!
  see https://jira.mongodb.org/browse/SERVER-54407
  see also https://www.mongodb.com/community/forums/t/mongodb-5-0-cpu-intel-g4650-compatibility/116610/2
  see also https://github.com/docker-library/mongo/issues/485#issuecomment-891991814
```

**Comment by VZiChoushaDui** [comment]
@iRhonin Seems that the server you use has a very old CPU.

Update again and tell me if it works.

**Comment by iRhonin** [comment]
Now mongodb is OK but the panel not starting: 

```
Traceback (most recent call last):
  File "/root/libertea/panel/./panel/__init__.py", line 15, in periodic_update_domains
    domains = utils.get_domains()
  File "/root/libertea/panel/./panel/utils.py", line 135, in get_domains
    all_domains = [domain["_id"] for domain in domains.find()]
  File "/root/libertea/panel/./panel/utils.py", line 135, in <listcomp>
    all_domains = [domain["_id"] for domain in domains.find()]
  File "/usr/local/lib/python3.10/dist-packages/pymongo/cursor.py", line 1248, in next
    if len(self.__data) or self._refresh():
  File "/usr/local/lib/python3.10/dist-packages/pymongo/cursor.py", line 1165, in _refresh
    self.__send_message(q)
  File "/usr/local/lib/python3.10/dist-packages/pymongo/cursor.py", line 1052, in __send_message
    response = client._run_operation(
  File "/usr/local/lib/python3.10/dist-packages/pymongo/_csot.py", line 105, in csot_wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pymongo/mongo_client.py", line 1330, in _run_operation
    return self._retryable_read(
  File "/usr/local/lib/python3.10/dist-packages/pymongo/_csot.py", line 105, in csot_wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pymongo/mongo_client.py", line 1442, in _retryable_read
    with self._socket_from_server(read_pref, server, session) as (sock_info, read_pref):
  File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.10/dist-packages/pymongo/mongo_client.py", line 1282, in _socket_from_server
    with self._get_socket(server, session) as sock_info:
  File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.10/dist-packages/pymongo/mongo_client.py", line 1217, in _get_socket
    with server.get_socket(handler=err_handler) as sock_info:
  File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.10/dist-packages/pymongo/pool.py", line 1407, in get_socket
    sock_info = self._get_socket(handler=handler)
  File "/usr/local/lib/python3.10/dist-packages/pymongo/pool.py", line 1520, in _get_socket
    sock_info = self.connect(handler=handler)
  File "/usr/local/lib/python3.10/dist-packages/pymongo/pool.py", line 1378, in connect
    sock_info.authenticate()
  File "/usr/local/lib/python3.10/dist-packages/pymongo/pool.py", line 870, in authenticate
    auth.authenticate(creds, self)
  File "/usr/local/lib/python3.10/dist-packages/pymongo/auth.py", line 549, in authenticate
    auth_func(credentials, sock_info)
  File "/usr/local/lib/python3.10/dist-packages/pymongo/auth.py", line 475, in _authenticate_default
    return _authenticate_scram(credentials, sock_info, "SCRAM-SHA-1")
  File "/usr/local/lib/python3.10/dist-packages/pymongo/auth.py", line 201, in _authenticate_scram
    res = sock_info.command(source, cmd)
  File "/usr/local/lib/python3.10/dist-packages/pymongo/pool.py", line 767, in command
    return command(
  File "/usr/local/lib/python3.10/dist-packages/pymongo/network.py", line 166, in command
    helpers._check_command_response(
  File "/usr/local/lib/python3.10/dist-packages/pymongo/helpers.py", line 181, in _check_command_response
    raise OperationFailure(errmsg, code, response, max_wire_version)
pymongo.errors.OperationFailure: Authentication failed., full error: {'ok': 0.0, 'errmsg': 'Authentication failed.', 'code': 18, 'codeName': 'AuthenticationFailed'}
Sat Jan 28 11:06:46 2023 - error managing signal 0 on worker 4
```

**Comment by VZiChoushaDui** [comment]
@iRhonin Maybe it's because you had the other version of mongodb first.

Please run the following commands on root shell one by one to remove and reset Libertea:

    cd ~/libertea
    docker compose down
    service stop libertea-panel.service
    rm -rf data
    git reset --hard
    ./init.sh update

**Comment by iRhonin** [comment]
No luck :( Let me try it on another VPS with a better hardware.
Thank you so much for the time you put into this issue and the project <3
