### ISSUE TITLE
ERROR: Timeout while waiting for panel to start.

### ISSUE THREAD

**Issue by iPmartNetwork** [VZiChoushaDui/Libertea#44]
✅ libertea-provider-shadowsocks-v2ray started
    ✅ libertea-mongodb started
    ✅ libertea-provider-vless-grpc started
    ✅ libertea-provider-vless-ws started
    ✅ libertea-provider-trojan-grpc started
    ✅ libertea-provider-trojan-ws started
    ✅ libertea-provider-vmess-grpc started
    ✅ libertea-rsyslog started
    ✅ libertea-log-parser started
    ✅ libertea-haproxy started
    ❌ libertea-panel failed to start. Retrying...
*******************************************************

**Comment by VZiChoushaDui** [comment]
Please post the output of the following two commands so we can investigate.

    tail -n 50 /tmp/libertea-panel.init.log

    tail -n 100 /tmp/libertea-panel.log

**Comment by 4erdenko** [comment]
Same problem.
Logs:

`    ❌ libertea-panel failed to start. Retrying...
*******************************************************
ERROR: Timeout while waiting for panel to start.
       Please open an issue on https://github.com/VZiChoushaDui/Libertea/issues/new
       and include the following information:

root@ubuntu-2gb-nbg1-1:~/vpn# tail -n 50 /tmp/libertea-panel.init.log

tail -n 100 /tmp/libertea-panel.log
[2023-11-01 21:37:33] Starting Libertea panel via uwsgi on port 1000 with 6 threads, and listen queue size of 512
[2023-11-01 21:37:34] Libertea panel serve script exited with code 22
[2023-11-01 21:37:44] Libertea panel serve script
[2023-11-01 21:37:44] Current directory: /root/libertea/panel
[2023-11-01 21:37:44] Checking net.core.somaxconn value
[2023-11-01 21:37:44]   net.core.somaxconn value is 4096
[2023-11-01 21:37:44] Starting Libertea panel via uwsgi on port 1000 with 6 threads, and listen queue size of 512
[2023-11-01 21:37:45] Libertea panel serve script exited with code 22
[2023-11-01 21:37:52] Libertea panel serve script
[2023-11-01 21:37:52] Current directory: /root/libertea/panel
[2023-11-01 21:37:52] Checking net.core.somaxconn value
[2023-11-01 21:37:52]   net.core.somaxconn value is 4096
[2023-11-01 21:37:52] Starting Libertea panel via uwsgi on port 1000 with 6 threads, and listen queue size of 512
[2023-11-01 21:37:52] Libertea panel serve script exited with code 22
[2023-11-01 21:38:03] Libertea panel serve script
[2023-11-01 21:38:03] Current directory: /root/libertea/panel
[2023-11-01 21:38:03] Checking net.core.somaxconn value
[2023-11-01 21:38:03]   net.core.somaxconn value is 4096
[2023-11-01 21:38:03] Starting Libertea panel via uwsgi on port 1000 with 6 threads, and listen queue size of 512
[2023-11-01 21:38:04] Libertea panel serve script exited with code 22
[2023-11-01 21:38:14] Libertea panel serve script
[2023-11-01 21:38:14] Current directory: /root/libertea/panel
[2023-11-01 21:38:14] Checking net.core.somaxconn value
[2023-11-01 21:38:14]   net.core.somaxconn value is 4096
[2023-11-01 21:38:14] Starting Libertea panel via uwsgi on port 1000 with 6 threads, and listen queue size of 512
[2023-11-01 21:38:15] Libertea panel serve script exited with code 22
[2023-11-01 21:38:25] Libertea panel serve script
[2023-11-01 21:38:25] Current directory: /root/libertea/panel
[2023-11-01 21:38:25] Checking net.core.somaxconn value
[2023-11-01 21:38:25]   net.core.somaxconn value is 4096
[2023-11-01 21:38:25] Starting Libertea panel via uwsgi on port 1000 with 6 threads, and listen queue size of 512
[2023-11-01 21:38:26] Libertea panel serve script exited with code 22
[2023-11-01 21:38:36] Libertea panel serve script
[2023-11-01 21:38:36] Current directory: /root/libertea/panel
[2023-11-01 21:38:36] Checking net.core.somaxconn value
[2023-11-01 21:38:36]   net.core.somaxconn value is 4096
[2023-11-01 21:38:36] Starting Libertea panel via uwsgi on port 1000 with 6 threads, and listen queue size of 512
[2023-11-01 21:38:37] Libertea panel serve script exited with code 22
[2023-11-01 21:38:47] Libertea panel serve script
[2023-11-01 21:38:47] Current directory: /root/libertea/panel
[2023-11-01 21:38:47] Checking net.core.somaxconn value
[2023-11-01 21:38:47]   net.core.somaxconn value is 4096
[2023-11-01 21:38:47] Starting Libertea panel via uwsgi on port 1000 with 6 threads, and listen queue size of 512
[2023-11-01 21:38:48] Libertea panel serve script exited with code 22
[2023-11-01 21:38:58] Libertea panel serve script
[2023-11-01 21:38:58] Current directory: /root/libertea/panel
[2023-11-01 21:38:58] Checking net.core.somaxconn value
[2023-11-01 21:38:58]   net.core.somaxconn value is 4096
[2023-11-01 21:38:58] Starting Libertea panel via uwsgi on port 1000 with 6 threads, and listen queue size of 512
[2023-11-01 21:38:59] Libertea panel serve script exited with code 22
[2023-11-01 21:38:58] Current directory: /root/libertea/panel
[2023-11-01 21:38:58] Checking net.core.somaxconn value
[2023-11-01 21:38:58]   net.core.somaxconn value is 4096
[2023-11-01 21:38:58] Starting Libertea panel via uwsgi on port 1000 with 6 threads, and listen queue size of 512
*** Starting uWSGI 2.0.23 (64bit) on [Wed Nov  1 21:38:58 2023] ***
compiled with version: 11.4.0 on 01 November 2023 21:24:37
os: Linux-5.15.0-87-generic #97-Ubuntu SMP Mon Oct 2 21:09:21 UTC 2023
nodename: ubuntu-2gb-nbg1-1
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /root/libertea/panel
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***
your processes number limit is 7481
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 127.0.0.1:1000 fd 4
uwsgi socket 0 bound to TCP address 127.0.0.1:39565 (port auto-assigned) fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***
Python version: 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x55d268e3cb70
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***
your server socket listen backlog is limited to 512 connections
your mercy for graceful operations on workers is 60 seconds
mapped 567672 bytes (554 KB) for 6 cores
*** Operational MODE: preforking ***
Initializing...
[uwsgi-signal] signum 0 registered (wid: 0 modifier1: 0 target: default, any worker)
[uwsgi-signal] signum 1 registered (wid: 0 modifier1: 0 target: default, any worker)
[uwsgi-signal] signum 2 registered (wid: 0 modifier1: 0 target: default, any worker)
[uwsgi-signal] signum 3 registered (wid: 0 modifier1: 0 target: default, any worker)
[uwsgi-signal] signum 4 registered (wid: 0 modifier1: 0 target: default, any worker)
Updating HAProxy lists
 -- creating mongo client on pid 188394
 -- reconnecting mongo client on pid 188394
Traceback (most recent call last):
  File "/root/libertea/panel/./serve.py", line 10, in <module>
    app = TransLogger(create_app(), setup_console_handler=False)
  File "/root/libertea/panel/./panel/__init__.py", line 61, in create_app
    sysops.haproxy_update_users_list()
  File "/root/libertea/panel/./panel/sysops.py", line 51, in haproxy_update_users_list
    for user in users.find():
  File "/usr/local/lib/python3.10/dist-packages/pymongo/cursor.py", line 1262, in next
    if len(self.__data) or self._refresh():
  File "/usr/local/lib/python3.10/dist-packages/pymongo/cursor.py", line 1179, in _refresh
    self.__send_message(q)
  File "/usr/local/lib/python3.10/dist-packages/pymongo/cursor.py", line 1060, in __send_message
    response = client._run_operation(
  File "/usr/local/lib/python3.10/dist-packages/pymongo/_csot.py", line 108, in csot_wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pymongo/mongo_client.py", line 1388, in _run_operation
    return self._retryable_read(
  File "/usr/local/lib/python3.10/dist-packages/pymongo/_csot.py", line 108, in csot_wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pymongo/mongo_client.py", line 1526, in _retryable_read
    with self._conn_from_server(read_pref, server, session) as (
  File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.10/dist-packages/pymongo/mongo_client.py", line 1324, in _conn_from_server
    with self._checkout(server, session) as conn:
  File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.10/dist-packages/pymongo/mongo_client.py", line 1246, in _checkout
    with server.checkout(handler=err_handler) as conn:
  File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.10/dist-packages/pymongo/pool.py", line 1598, in checkout
    conn = self._get_conn(handler=handler)
  File "/usr/local/lib/python3.10/dist-packages/pymongo/pool.py", line 1714, in _get_conn
    conn = self.connect(handler=handler)
  File "/usr/local/lib/python3.10/dist-packages/pymongo/pool.py", line 1568, in connect
    conn.authenticate()
  File "/usr/local/lib/python3.10/dist-packages/pymongo/pool.py", line 1042, in authenticate
    auth.authenticate(creds, self, reauthenticate=reauthenticate)
  File "/usr/local/lib/python3.10/dist-packages/pymongo/auth.py", line 616, in authenticate
    auth_func(credentials, conn)
  File "/usr/local/lib/python3.10/dist-packages/pymongo/auth.py", line 521, in _authenticate_default
    return _authenticate_scram(credentials, conn, "SCRAM-SHA-1")
  File "/usr/local/lib/python3.10/dist-packages/pymongo/auth.py", line 248, in _authenticate_scram
    res = conn.command(source, cmd)
  File "/usr/local/lib/python3.10/dist-packages/pymongo/helpers.py", line 315, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pymongo/pool.py", line 932, in command
    return command(
  File "/usr/local/lib/python3.10/dist-packages/pymongo/network.py", line 191, in command
    helpers._check_command_response(
  File "/usr/local/lib/python3.10/dist-packages/pymongo/helpers.py", line 223, in _check_command_response
    raise OperationFailure(errmsg, code, response, max_wire_version)
pymongo.errors.OperationFailure: Authentication failed., full error: {'ok': 0.0, 'errmsg': 'Authentication failed.', 'code': 18, 'codeName': 'AuthenticationFailed'}
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. GAME OVER ***
[2023-11-01 21:38:59] Libertea panel serve script exited with code 22
root@ubuntu-2gb-nbg1-1:~/vpn#`
