### ISSUE TITLE
Running Panel error while installing

### ISSUE THREAD

**Issue by MahanMahur** [VZiChoushaDui/Libertea#62]
OS: ubuntu 20.04
datacenter: pq hosting( I install Libertea on same vm 3 month ago and everything was well )
Error Message:

ERROR: Timeout while waiting for panel to start.
       Please open an issue on https://github.com/VZiChoushaDui/Libertea/issues/new
       and include the following information:

![Screenshot 2024-01-25 150758](https://github.com/VZiChoushaDui/Libertea/assets/112780317/882292bd-d664-4ab6-9aac-d41899da41cb)

**Comment by VZiChoushaDui** [comment]
Please run the following command on your server and send the results:

    tail -n 100 /tmp/libertea-panel.log

**Comment by VZiChoushaDui** [comment]
Fixed in the new version. Please install Libertea again.

**Comment by shammay-PC** [comment]
:~# tail -n 100 /tmp/libertea-panel.log
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***
your processes number limit is 23211
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 127.0.0.1:1000 fd 4
uwsgi socket 0 bound to TCP address 127.0.0.1:34999 (port auto-assigned) fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***
Python version: 3.8.10 (default, Nov 22 2023, 10:22:35)  [GCC 9.4.0]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x55eddadb9e00
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***
your server socket listen backlog is limited to 512 connections
your mercy for graceful operations on workers is 60 seconds
mapped 567672 bytes (554 KB) for 6 cores
*** Operational MODE: preforking ***
Initializing...
[uwsgi-signal] signum 0 registered (wid: 0 modifier1: 0 target: default, any worker)
[uwsgi-signal] signum 1 registered (wid: 0 modifier1: 0 target: default, any worker)
[uwsgi-signal] signum 2 registered (wid: 0 modifier1: 0 target: default, any worker)
[uwsgi-signal] signum 3 registered (wid: 0 modifier1: 0 target: default, any worker)
[uwsgi-signal] signum 4 registered (wid: 0 modifier1: 0 target: default, any worker)
Updating HAProxy lists
 -- creating mongo client on pid 12504
 -- reconnecting mongo client on pid 12504
Traceback (most recent call last):
  File "/root/libertea/panel/./serve.py", line 10, in <module>
    app = TransLogger(create_app(), setup_console_handler=False)
  File "/root/libertea/panel/./panel/__init__.py", line 65, in create_app
    sysops.haproxy_update_users_list()
  File "/root/libertea/panel/./panel/sysops.py", line 61, in haproxy_update_users_list
    for user in users.find():
  File "/usr/local/lib/python3.8/dist-packages/pymongo/cursor.py", line 1264, in next
    if len(self.__data) or self._refresh():
  File "/usr/local/lib/python3.8/dist-packages/pymongo/cursor.py", line 1155, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "/usr/local/lib/python3.8/dist-packages/pymongo/mongo_client.py", line 1823, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/usr/local/lib/python3.8/dist-packages/pymongo/mongo_client.py", line 1766, in __start_session
    self._topology._check_implicit_session_support()
  File "/usr/local/lib/python3.8/dist-packages/pymongo/topology.py", line 573, in _check_implicit_session_support
    self._check_session_support()
  File "/usr/local/lib/python3.8/dist-packages/pymongo/topology.py", line 589, in _check_session_support
    self._select_servers_loop(
  File "/usr/local/lib/python3.8/dist-packages/pymongo/topology.py", line 259, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 5.0s, Topology Description: <TopologyDescription id: 65ced77febb6f5d26b194fff, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. GAME OVER ***
[2024-02-16 03:33:24] Libertea panel serve script exited with code 22
[2024-02-16 03:33:34] Libertea panel serve script
[2024-02-16 03:33:34] Current directory: /root/libertea/panel
[2024-02-16 03:33:34] Checking net.core.somaxconn value
[2024-02-16 03:33:34]   net.core.somaxconn value is 4096
[2024-02-16 03:33:34] Starting Libertea panel via uwsgi on port 1000 with 6 threads, and listen queue size of 512
*** Starting uWSGI 2.0.24 (64bit) on [Fri Feb 16 03:33:34 2024] ***
compiled with version: 9.4.0 on 13 February 2024 23:10:31
os: Linux-5.4.0-171-generic #189-Ubuntu SMP Fri Jan 5 14:23:02 UTC 2024
nodename: S8H-FL-NgNv
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /root/libertea/panel
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***
your processes number limit is 23211
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 127.0.0.1:1000 fd 4
uwsgi socket 0 bound to TCP address 127.0.0.1:36691 (port auto-assigned) fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***
Python version: 3.8.10 (default, Nov 22 2023, 10:22:35)  [GCC 9.4.0]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x559cbe187e00
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***
your server socket listen backlog is limited to 512 connections
your mercy for graceful operations on workers is 60 seconds
mapped 567672 bytes (554 KB) for 6 cores
*** Operational MODE: preforking ***
Initializing...
[uwsgi-signal] signum 0 registered (wid: 0 modifier1: 0 target: default, any worker)
[uwsgi-signal] signum 1 registered (wid: 0 modifier1: 0 target: default, any worker)
[uwsgi-signal] signum 2 registered (wid: 0 modifier1: 0 target: default, any worker)
[uwsgi-signal] signum 3 registered (wid: 0 modifier1: 0 target: default, any worker)
[uwsgi-signal] signum 4 registered (wid: 0 modifier1: 0 target: default, any worker)
Updating HAProxy lists
 -- creating mongo client on pid 12739
 -- reconnecting mongo client on pid 12739
@shammay

**Comment by VZiChoushaDui** [comment]
@MahanMahur It seems that mongodb container has failed to start.

Please check its container using:

    docker ps

and its logs using:

    docker logs --tail=200 libertea-mongodb
