### ISSUE TITLE
error

### ISSUE THREAD

**Issue by mammut700** [VZiChoushaDui/Libertea#63]
** Adding auto-update cronjob...
 ** Waiting for services to start...
    ✅ libertea-provider-trojan-grpc started
    ✅ libertea-rsyslog started
    ✅ libertea-provider-vless-ws started
    ✅ libertea-provider-trojan-ws started
    ✅ libertea-log-parser started
    ✅ libertea-mongodb started
    ✅ libertea-provider-shadowsocks-v2ray started
    ✅ libertea-provider-vmess-grpc started
    ✅ libertea-provider-vless-grpc started
    ✅ libertea-haproxy started
    ❌ libertea-panel failed to start. Retrying...
*******************************************************
ERROR: Timeout while waiting for panel to start.
       Please open an issue on https://github.com/VZiChoushaDui/Libertea/issues/new
       and include the following information:

**Comment by VZiChoushaDui** [comment]
Please run the following command on your server and send the results:

    tail -n 100 /tmp/libertea-panel.log

**Comment by mammut700** [comment]
tail -n 100 /tmp/libertea-panel.log
[2024-01-29 18:35:47] Current directory: /root/libertea/panel
[2024-01-29 18:35:47] Checking net.core.somaxconn value
[2024-01-29 18:35:48]   net.core.somaxconn value is 4096
[2024-01-29 18:35:48] Starting Libertea panel via uwsgi on port 1000 with 6 threads, and listen queue size of 512
*** Starting uWSGI 2.0.23 (64bit) on [Mon Jan 29 18:35:48 2024] ***
compiled with version: 9.4.0 on 28 January 2024 19:40:40
os: Linux-5.4.0-170-generic #188-Ubuntu SMP Wed Jan 10 09:51:01 UTC 2024
nodename: ubuntu-vps-start-se-sto1-1
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /root/libertea/panel
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***
your processes number limit is 3494
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 127.0.0.1:1000 fd 4
uwsgi socket 0 bound to TCP address 127.0.0.1:44239 (port auto-assigned) fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***
Python version: 3.8.10 (default, Nov 22 2023, 10:22:35)  [GCC 9.4.0]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x563d3eb16460
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***
your server socket listen backlog is limited to 512 connections
your mercy for graceful operations on workers is 60 seconds
mapped 567672 bytes (554 KB) for 6 cores
*** Operational MODE: preforking ***
Traceback (most recent call last):
  File "/root/libertea/panel/./serve.py", line 4, in <module>
    from panel import create_app
  File "/root/libertea/panel/./panel/__init__.py", line 1, in <module>
    import requests
  File "/usr/lib/python3/dist-packages/requests/__init__.py", line 95, in <module>
    from urllib3.contrib import pyopenssl
  File "/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
  File "/usr/local/lib/python3.8/dist-packages/pyOpenSSL-22.1.0-py3.8.egg/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import SSL, crypto
  File "/usr/local/lib/python3.8/dist-packages/pyOpenSSL-22.1.0-py3.8.egg/OpenSSL/SSL.py", line 19, in <module>
    from OpenSSL.crypto import (
  File "/usr/local/lib/python3.8/dist-packages/pyOpenSSL-22.1.0-py3.8.egg/OpenSSL/crypto.py", line 1593, in <module>
    class X509StoreFlags:
  File "/usr/local/lib/python3.8/dist-packages/pyOpenSSL-22.1.0-py3.8.egg/OpenSSL/crypto.py", line 1612, in X509StoreFlags
    NOTIFY_POLICY: int = _lib.X509_V_FLAG_NOTIFY_POLICY
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_NOTIFY_POLICY'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 72, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 32, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 12, in <module>
    import os, glob, subprocess, os.path, time, pwd, sys, requests_unixsocket
  File "/usr/lib/python3/dist-packages/requests_unixsocket/__init__.py", line 1, in <module>
    import requests
  File "/usr/lib/python3/dist-packages/requests/__init__.py", line 95, in <module>
    from urllib3.contrib import pyopenssl
  File "/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
  File "/usr/local/lib/python3.8/dist-packages/pyOpenSSL-22.1.0-py3.8.egg/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import SSL, crypto
  File "/usr/local/lib/python3.8/dist-packages/pyOpenSSL-22.1.0-py3.8.egg/OpenSSL/SSL.py", line 19, in <module>
    from OpenSSL.crypto import (
  File "/usr/local/lib/python3.8/dist-packages/pyOpenSSL-22.1.0-py3.8.egg/OpenSSL/crypto.py", line 1593, in <module>
    class X509StoreFlags:
  File "/usr/local/lib/python3.8/dist-packages/pyOpenSSL-22.1.0-py3.8.egg/OpenSSL/crypto.py", line 1612, in X509StoreFlags
    NOTIFY_POLICY: int = _lib.X509_V_FLAG_NOTIFY_POLICY
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_NOTIFY_POLICY'

Original exception was:
Traceback (most recent call last):
  File "/root/libertea/panel/./serve.py", line 4, in <module>
    from panel import create_app
  File "/root/libertea/panel/./panel/__init__.py", line 1, in <module>
    import requests
  File "/usr/lib/python3/dist-packages/requests/__init__.py", line 95, in <module>
    from urllib3.contrib import pyopenssl
  File "/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
  File "/usr/local/lib/python3.8/dist-packages/pyOpenSSL-22.1.0-py3.8.egg/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import SSL, crypto
  File "/usr/local/lib/python3.8/dist-packages/pyOpenSSL-22.1.0-py3.8.egg/OpenSSL/SSL.py", line 19, in <module>
    from OpenSSL.crypto import (
  File "/usr/local/lib/python3.8/dist-packages/pyOpenSSL-22.1.0-py3.8.egg/OpenSSL/crypto.py", line 1593, in <module>
    class X509StoreFlags:
  File "/usr/local/lib/python3.8/dist-packages/pyOpenSSL-22.1.0-py3.8.egg/OpenSSL/crypto.py", line 1612, in X509StoreFlags
    NOTIFY_POLICY: int = _lib.X509_V_FLAG_NOTIFY_POLICY
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_NOTIFY_POLICY'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. GAME OVER ***
[2024-01-29 18:35:48] Libertea panel serve script exited with code 22

**Comment by VZiChoushaDui** [comment]
@mammut700 What is your OS and OS version? You can find out by running command `lsb_release -a`

**Comment by mammut700** [comment]
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.6 LTS
Release:        20.04
Codename:       focal

**Comment by VZiChoushaDui** [comment]
Fixed in the new version. Please install Libertea again.
