### ISSUE TITLE
ERROR: Timeout while waiting for panel to start.

### ISSUE THREAD

**Issue by aksiere** [VZiChoushaDui/Libertea#97]
Tested on Ubuntu 20/22 and Debian 12. The result is the same. I tried it on two different servers.

```
 ** Waiting for services to start...
    ✅ libertea-provider-trojan-ws started
    ✅ libertea-camouflage-nginx-fallback started
    ✅ libertea-provider-vmess-grpc started
    ✅ libertea-provider-vless-ws started
    ✅ libertea-provider-shadowsocks-v2ray started
    ✅ libertea-provider-trojan-grpc started
    ✅ libertea-log-parser started
    ✅ libertea-provider-vless-grpc started
    ✅ libertea-mongodb started
    ✅ libertea-rsyslog started
    ✅ libertea-haproxy started
    ❌ libertea-panel failed to start. Retrying...
*******************************************************
ERROR: Timeout while waiting for panel to start.
       Please open an issue on https://github.com/VZiChoushaDui/Libertea/issues/new
       and include the following information:

       - component name: libertea-panel
       - OS: "Debian GNU/Linux"
       - OS version: "12"
       - Docker version: Docker version 27.2.1, build 9e34c9b
       - Panel listening: False
       - Panel root status code: 000
       - Panel admin status code: 000
       Also include the output of the following command:
           tail -n 100 /tmp/libertea-panel.log
```

```
root@debian:~# tail -n 100 /tmp/libertea-panel.log
tail: cannot open '/tmp/libertea-panel.log' for reading: No such file or directory
```

**Comment by VZiChoushaDui** [comment]
Hmm. No panel log file? The service hasn't been started at all then.

Is systemd working? Run `sudo systemctl status libertea-panel` and post the output.

---


We can't reproduce this atm, perhaps some weird configuration of os on your server provider's side is causing that. Would you mind sharing where you're getting your servers from?

**Comment by aksiere** [comment]
> Hmm. No panel log file? The service hasn't been started at all then.
> 
> Is systemd working? Run `sudo systemctl status libertea-panel` and post the output.
> 
> We can't reproduce this atm, perhaps some weird configuration of os on your server provider's side is causing that. Would you mind sharing where you're getting your servers from?

Ubuntu 22 this time:
```
ERROR: Timeout while waiting for panel to start.
       Please open an issue on https://github.com/VZiChoushaDui/Libertea/issues/new
       and include the following information:

       - component name: libertea-panel
       - OS: "Ubuntu"
       - OS version: "22.04"
       - Docker version: Docker version 27.2.1, build 9e34c9b
       - Panel listening: False
       - Panel root status code: 000
       - Panel admin status code: 000
       Also include the output of the following command:
           tail -n 100 /tmp/libertea-panel.log
```

```
root@ubuntu:~# sudo systemctl status libertea-panel
● libertea-panel.service - LiberteaPanel
     Loaded: loaded (/etc/systemd/system/libertea-panel.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Mon 2024-09-16 00:40:52 UTC; 7s ago
    Process: 19345 ExecStart=/bin/bash /root/libertea/panel/serve.sh (code=exited, status=208/STDIN)
   Main PID: 19345 (code=exited, status=208/STDIN)
        CPU: 1ms
```

VPS at hostup.se

**Comment by VZiChoushaDui** [comment]
Please also post the output of this command:

    tail -n 100 /tmp/libertea-panel.init.log

**Comment by aksiere** [comment]
> Please also post the output of this command:
> 
> ```
> tail -n 100 /tmp/libertea-panel.init.log
> ```

```
root@ubuntu:~# tail -n 100 /tmp/libertea-panel.init.log
tail: cannot open '/tmp/libertea-panel.init.log' for reading: No such file or directory
```

there are no any relevant logs in the /tmp folder

**Comment by aosmirnov** [comment]
I've got the same issue after a year of running Libertea. Panel cannot start and mongo container is restarting continuously.

```
ERROR: Timeout while waiting for panel to start.
       Please open an issue on https://github.com/VZiChoushaDui/Libertea/issues/new
       and include the following information:

       - component name: libertea-panel
       - OS: "Ubuntu"
       - OS version: "22.04"
       - Docker version: Docker version 29.1.2, build 890dcca
       - Panel listening: False
       - Panel root status code: 000
       - Panel admin status code: 000
       Also include the output of the following command:
           tail -n 100 /tmp/libertea-panel.log
```

**tail -n 100 /tmp/libertea-panel.log**
```
[uwsgi-signal] signum 18 registered (wid: 0 modifier1: 0 target: workers)
Updating HAProxy lists
 -- creating mongo client on pid 8693
 -- reconnecting mongo client on pid 8693
Traceback (most recent call last):
  File "/root/libertea/panel/./serve.py", line 10, in <module>
    app = TransLogger(create_app(), setup_console_handler=False)
  File "/root/libertea/panel/./panel/__init__.py", line 104, in create_app
    sysops.haproxy_update_users_list()
  File "/root/libertea/panel/./panel/sysops.py", line 61, in haproxy_update_users_list
    for user in users.find():
  File "/usr/local/lib/python3.10/dist-packages/pymongo/synchronous/cursor.py", line 1281, in __next__
    return self.next()
  File "/usr/local/lib/python3.10/dist-packages/pymongo/synchronous/cursor.py", line 1257, in next
    if len(self._data) or self._refresh():
  File "/usr/local/lib/python3.10/dist-packages/pymongo/synchronous/cursor.py", line 1205, in _refresh
    self._send_message(q)
  File "/usr/local/lib/python3.10/dist-packages/pymongo/synchronous/cursor.py", line 1100, in _send_message
    response = client._run_operation(
  File "/usr/local/lib/python3.10/dist-packages/pymongo/_csot.py", line 119, in csot_wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pymongo/synchronous/mongo_client.py", line 1754, in _run_operation
    return self._retryable_read(
  File "/usr/local/lib/python3.10/dist-packages/pymongo/synchronous/mongo_client.py", line 1863, in _retryable_read
    return self._retry_internal(
  File "/usr/local/lib/python3.10/dist-packages/pymongo/_csot.py", line 119, in csot_wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pymongo/synchronous/mongo_client.py", line 1830, in _retry_internal
    ).run()
  File "/usr/local/lib/python3.10/dist-packages/pymongo/synchronous/mongo_client.py", line 2554, in run
    return self._read() if self._is_read else self._write()
  File "/usr/local/lib/python3.10/dist-packages/pymongo/synchronous/mongo_client.py", line 2689, in _read
    self._server = self._get_server()
  File "/usr/local/lib/python3.10/dist-packages/pymongo/synchronous/mongo_client.py", line 2645, in _get_server
    return self._client._select_server(
  File "/usr/local/lib/python3.10/dist-packages/pymongo/synchronous/mongo_client.py", line 1649, in _select_server
    server = topology.select_server(
  File "/usr/local/lib/python3.10/dist-packages/pymongo/synchronous/topology.py", line 398, in select_server
    server = self._select_server(
  File "/usr/local/lib/python3.10/dist-packages/pymongo/synchronous/topology.py", line 376, in _select_server
    servers = self.select_servers(
  File "/usr/local/lib/python3.10/dist-packages/pymongo/synchronous/topology.py", line 283, in select_servers
    server_descriptions = self._select_servers_loop(
  File "/usr/local/lib/python3.10/dist-packages/pymongo/synchronous/topology.py", line 333, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 5.0s, Topology Description: <TopologyDescription id: 6939c76f3e22680c73da0def, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. GAME OVER ***
[2025-12-10 22:18:12] Libertea panel serve script exited with code 22
[2025-12-10 22:18:22] Libertea panel serve script
[2025-12-10 22:18:22] Current directory: /root/libertea/panel
[2025-12-10 22:18:22] Checking total memory
[2025-12-10 22:18:22] Tuning kernel parameters
[2025-12-10 22:18:22]    - ulimit: 100000
[2025-12-10 22:18:22]    - net.core.somaxconn: 65534
[2025-12-10 22:18:22]    - net.ipv4.ip_local_port_range: 16384  65535
[2025-12-10 22:18:22]    - net.netfilter.nf_conntrack_max: 262144
[2025-12-10 22:18:22]    - net.ipv4.tcp_fin_timeout: 15
[2025-12-10 22:18:22] Checking total memory
[2025-12-10 22:18:22] Starting Libertea panel via uwsgi on port 1000 with 6 threads, and listen queue size of 512
*** Starting uWSGI 2.0.28 (64bit) on [Wed Dec 10 22:18:22 2025] ***
compiled with version: 11.4.0 on 08 January 2025 14:49:59
os: Linux-5.15.0-130-generic #140-Ubuntu SMP Wed Dec 18 17:59:53 UTC 2024
nodename: clash-master
machine: x86_64
clock source: unix
detected number of CPU cores: 2
current working directory: /root/libertea/panel
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***
your processes number limit is 7584
your memory page size is 4096 bytes
detected max file descriptor number: 100000
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 127.0.0.1:1000 fd 4
uwsgi socket 0 bound to TCP address 127.0.0.1:39353 (port auto-assigned) fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***
Python version: 3.10.12 (main, Nov  4 2025, 08:48:33) [GCC 11.4.0]
Python main interpreter initialized at 0x55e6588fa030
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***
python threads support enabled
your server socket listen backlog is limited to 512 connections
your mercy for graceful operations on workers is 60 seconds
mapped 567672 bytes (554 KB) for 6 cores
*** Operational MODE: preforking ***
Initializing...
[uwsgi-signal] signum 0 registered (wid: 0 modifier1: 0 target: default, any worker)
[uwsgi-signal] signum 1 registered (wid: 0 modifier1: 0 target: default, any worker)
[uwsgi-signal] signum 2 registered (wid: 0 modifier1: 0 target: default, any worker)
[uwsgi-signal] signum 3 registered (wid: 0 modifier1: 0 target: default, any worker)
[uwsgi-signal] signum 4 registered (wid: 0 modifier1: 0 target: default, any worker)
[uwsgi-signal] signum 18 registered (wid: 0 modifier1: 0 target: workers)
Updating HAProxy lists
 -- creating mongo client on pid 8735
 -- reconnecting mongo client on pid 8735
```

**tail -n 100 /tmp/libertea-panel.init.log**
```
[2025-12-10 22:20:48]    - net.netfilter.nf_conntrack_max: 262144
[2025-12-10 22:20:48]    - net.ipv4.tcp_fin_timeout: 15
[2025-12-10 22:20:48] Checking total memory
[2025-12-10 22:20:48] Starting Libertea panel via uwsgi on port 1000 with 6 threads, and listen queue size of 512
[2025-12-10 22:20:58] Libertea panel serve script exited with code 22
[2025-12-10 22:21:09] Libertea panel serve script
[2025-12-10 22:21:09] Current directory: /root/libertea/panel
[2025-12-10 22:21:09] Checking total memory
[2025-12-10 22:21:09] Tuning kernel parameters
[2025-12-10 22:21:09]    - ulimit: 100000
[2025-12-10 22:21:09]    - net.core.somaxconn: 65534
[2025-12-10 22:21:09]    - net.ipv4.ip_local_port_range: 16384  65535
[2025-12-10 22:21:09]    - net.netfilter.nf_conntrack_max: 262144
[2025-12-10 22:21:09]    - net.ipv4.tcp_fin_timeout: 15
[2025-12-10 22:21:09] Checking total memory
[2025-12-10 22:21:09] Starting Libertea panel via uwsgi on port 1000 with 6 threads, and listen queue size of 512
[2025-12-10 22:21:19] Libertea panel serve script exited with code 22
[2025-12-10 22:21:30] Libertea panel serve script
[2025-12-10 22:21:30] Current directory: /root/libertea/panel
[2025-12-10 22:21:30] Checking total memory
[2025-12-10 22:21:30] Tuning kernel parameters
[2025-12-10 22:21:30]    - ulimit: 100000
[2025-12-10 22:21:30]    - net.core.somaxconn: 65534
[2025-12-10 22:21:30]    - net.ipv4.ip_local_port_range: 16384  65535
[2025-12-10 22:21:30]    - net.netfilter.nf_conntrack_max: 262144
[2025-12-10 22:21:30]    - net.ipv4.tcp_fin_timeout: 15
[2025-12-10 22:21:30] Checking total memory
[2025-12-10 22:21:30] Starting Libertea panel via uwsgi on port 1000 with 6 threads, and listen queue size of 512
[2025-12-10 22:21:40] Libertea panel serve script exited with code 22
[2025-12-10 22:21:51] Libertea panel serve script
[2025-12-10 22:21:51] Current directory: /root/libertea/panel
[2025-12-10 22:21:51] Checking total memory
[2025-12-10 22:21:51] Tuning kernel parameters
[2025-12-10 22:21:51]    - ulimit: 100000
[2025-12-10 22:21:51]    - net.core.somaxconn: 65534
[2025-12-10 22:21:51]    - net.ipv4.ip_local_port_range: 16384  65535
[2025-12-10 22:21:51]    - net.netfilter.nf_conntrack_max: 262144
[2025-12-10 22:21:51]    - net.ipv4.tcp_fin_timeout: 15
[2025-12-10 22:21:51] Checking total memory
[2025-12-10 22:21:51] Starting Libertea panel via uwsgi on port 1000 with 6 threads, and listen queue size of 512
[2025-12-10 22:22:01] Libertea panel serve script exited with code 22
[2025-12-10 22:22:12] Libertea panel serve script
[2025-12-10 22:22:12] Current directory: /root/libertea/panel
[2025-12-10 22:22:12] Checking total memory
[2025-12-10 22:22:12] Tuning kernel parameters
[2025-12-10 22:22:12]    - ulimit: 100000
[2025-12-10 22:22:12]    - net.core.somaxconn: 65534
[2025-12-10 22:22:12]    - net.ipv4.ip_local_port_range: 16384  65535
[2025-12-10 22:22:12]    - net.netfilter.nf_conntrack_max: 262144
[2025-12-10 22:22:12]    - net.ipv4.tcp_fin_timeout: 15
[2025-12-10 22:22:12] Checking total memory
[2025-12-10 22:22:12] Starting Libertea panel via uwsgi on port 1000 with 6 threads, and listen queue size of 512
[2025-12-10 22:22:24] Libertea panel serve script exited with code 22
[2025-12-10 22:22:35] Libertea panel serve script
[2025-12-10 22:22:35] Current directory: /root/libertea/panel
[2025-12-10 22:22:35] Checking total memory
[2025-12-10 22:22:35] Tuning kernel parameters
[2025-12-10 22:22:35]    - ulimit: 100000
[2025-12-10 22:22:35]    - net.core.somaxconn: 65534
[2025-12-10 22:22:35]    - net.ipv4.ip_local_port_range: 16384  65535
[2025-12-10 22:22:35]    - net.netfilter.nf_conntrack_max: 262144
[2025-12-10 22:22:35]    - net.ipv4.tcp_fin_timeout: 15
[2025-12-10 22:22:35] Checking total memory
[2025-12-10 22:22:35] Starting Libertea panel via uwsgi on port 1000 with 6 threads, and listen queue size of 512
[2025-12-10 22:22:45] Libertea panel serve script exited with code 22
[2025-12-10 22:22:56] Libertea panel serve script
[2025-12-10 22:22:56] Current directory: /root/libertea/panel
[2025-12-10 22:22:56] Checking total memory
[2025-12-10 22:22:56] Tuning kernel parameters
[2025-12-10 22:22:56]    - ulimit: 100000
[2025-12-10 22:22:56]    - net.core.somaxconn: 65534
[2025-12-10 22:22:56]    - net.ipv4.ip_local_port_range: 16384  65535
[2025-12-10 22:22:56]    - net.netfilter.nf_conntrack_max: 262144
[2025-12-10 22:22:56]    - net.ipv4.tcp_fin_timeout: 15
[2025-12-10 22:22:56] Checking total memory
[2025-12-10 22:22:56] Starting Libertea panel via uwsgi on port 1000 with 6 threads, and listen queue size of 512
[2025-12-10 22:23:06] Libertea panel serve script exited with code 22
[2025-12-10 22:23:16] Libertea panel serve script
[2025-12-10 22:23:16] Current directory: /root/libertea/panel
[2025-12-10 22:23:16] Checking total memory
[2025-12-10 22:23:16] Tuning kernel parameters
[2025-12-10 22:23:16]    - ulimit: 100000
[2025-12-10 22:23:16]    - net.core.somaxconn: 65534
[2025-12-10 22:23:16]    - net.ipv4.ip_local_port_range: 16384  65535
[2025-12-10 22:23:16]    - net.netfilter.nf_conntrack_max: 262144
[2025-12-10 22:23:16]    - net.ipv4.tcp_fin_timeout: 15
[2025-12-10 22:23:16] Checking total memory
[2025-12-10 22:23:16] Starting Libertea panel via uwsgi on port 1000 with 6 threads, and listen queue size of 512
[2025-12-10 22:23:27] Libertea panel serve script exited with code 22
[2025-12-10 22:23:37] Libertea panel serve script
[2025-12-10 22:23:37] Current directory: /root/libertea/panel
[2025-12-10 22:23:37] Checking total memory
[2025-12-10 22:23:37] Tuning kernel parameters
[2025-12-10 22:23:37]    - ulimit: 100000
[2025-12-10 22:23:37]    - net.core.somaxconn: 65534
[2025-12-10 22:23:37]    - net.ipv4.ip_local_port_range: 16384  65535
[2025-12-10 22:23:37]    - net.netfilter.nf_conntrack_max: 262144
[2025-12-10 22:23:37]    - net.ipv4.tcp_fin_timeout: 15
[2025-12-10 22:23:37] Checking total memory
[2025-12-10 22:23:37] Starting Libertea panel via uwsgi on port 1000 with 6 threads, and listen queue size of 512
```
